/** Builds concise display selectors and stable CSS selector suggestions. */

/** Classes that are generated by CSS-in-JS / hashing tools and won't survive a rebuild. */
const HASHED_CLASS = [
  /^css-[a-z0-9]{4,}$/i, // emotion
  /^sc-[a-zA-Z0-9]{4,}$/, // styled-components
  /^jsx-\d+$/, // styled-jsx
  /^svelte-[a-z0-9]{4,}$/i,
  /^astro-[a-z0-9]{6,}$/i,
  /^_(?=[a-zA-Z]*\d)[a-zA-Z0-9]{5,}$/, // css modules (hash only)
  /^[a-zA-Z]+_[a-zA-Z]+__[a-zA-Z0-9_-]{5,}$/, // css modules (Component_name__hash)
  /^(?=.*\d)[a-zA-Z]{1,3}[A-Z0-9][a-zA-Z0-9]{4,}$/, // short random tokens like "kRtYp2"
  /^ng-(?:tns|star|untouched|pristine|valid|invalid)/,
  /^data-v-[a-f0-9]+$/,
];

const STATE_CLASS =
  /^(?:is-|has-)?(?:active|hover|focus|focused|open|opened|selected|current|visible|hidden|show|shown|loaded|loading|animated|in-view)$/i;

export function isMeaningfulClass(cls: string): boolean {
  if (!cls || cls.length > 48) return false;
  if (HASHED_CLASS.some((re) => re.test(cls))) return false;
  if (/^\d/.test(cls)) return false;
  if (/[a-z][0-9a-f]{6,}$/i.test(cls) && /\d{2,}/.test(cls)) return false;
  return true;
}

export function meaningfulClasses(el: Element, max = 6): string[] {
  const out: string[] = [];
  for (const c of Array.from(el.classList)) {
    if (isMeaningfulClass(c) && !STATE_CLASS.test(c)) out.push(c);
    if (out.length >= max) break;
  }
  return out;
}

export function isStableId(id: string): boolean {
  if (!id || id.length > 40) return false;
  if (/^\d/.test(id)) return false;
  if (/^(?::r[0-9a-z]+:|radix-|headlessui-|react-aria|mui-|ember\d|ext-gen)/i.test(id))
    return false;
  if ((id.match(/\d/g)?.length ?? 0) > 4) return false;
  if (/[a-f0-9]{8,}/i.test(id)) return false;
  return /^[A-Za-z][\w-]*$/.test(id);
}

export function cssEscape(value: string): string {
  if (typeof CSS !== 'undefined' && typeof CSS.escape === 'function') return CSS.escape(value);
  return value.replace(/([^\w-])/g, '\\$1');
}

/** Short human-readable label such as `section.min-w-0` or `nav#primary`. */
export function conciseSelector(el: Element, maxClasses = 2): string {
  const tag = el.tagName.toLowerCase();
  if (el.id && isStableId(el.id)) return `${tag}#${el.id}`;
  const classes = meaningfulClasses(el, maxClasses);
  return classes.length ? `${tag}.${classes.join('.')}` : tag;
}

function segment(el: Element): string {
  const tag = el.tagName.toLowerCase();
  if (el.id && isStableId(el.id)) return `#${cssEscape(el.id)}`;
  const classes = meaningfulClasses(el, 2)
    .map((c) => `.${cssEscape(c)}`)
    .join('');
  return `${tag}${classes}`;
}

function nthOfType(el: Element): string {
  const parent = el.parentElement;
  if (!parent) return '';
  const same = Array.from(parent.children).filter((c) => c.tagName === el.tagName);
  if (same.length <= 1) return '';
  return `:nth-of-type(${same.indexOf(el) + 1})`;
}

function isUnique(root: ParentNode, selector: string, el: Element): boolean {
  try {
    const found = root.querySelectorAll(selector);
    return found.length === 1 && found[0] === el;
  } catch {
    return false;
  }
}

/**
 * Generates a selector that uniquely matches `el` within its document, preferring IDs,
 * meaningful classes, and short paths over long nth-child chains.
 */
export function buildStableSelector(el: Element, maxDepth = 5): string {
  const doc = el.ownerDocument;
  if (el.id && isStableId(el.id) && isUnique(doc, `#${cssEscape(el.id)}`, el))
    return `#${cssEscape(el.id)}`;
  const parts: string[] = [];
  let current: Element | null = el;
  for (let depth = 0; current && depth < maxDepth; depth++) {
    const tag = current.tagName.toLowerCase();
    if (tag === 'html' || tag === 'body') break;
    const seg = segment(current);
    parts.unshift(seg);
    const candidate = parts.join(' > ');
    if (isUnique(doc, candidate, el)) return candidate;
    // Disambiguate this level with :nth-of-type and retry.
    parts[0] = seg.startsWith('#') ? seg : `${seg}${nthOfType(current)}`;
    const withNth = parts.join(' > ');
    if (isUnique(doc, withNth, el)) return withNth;
    if (seg.startsWith('#')) break;
    current = current.parentElement;
  }
  return parts.join(' > ') || el.tagName.toLowerCase();
}

/** Signature used for repeated-structure detection: tag + meaningful classes + child tag shape. */
export function structuralSignature(el: Element): string {
  const tag = el.tagName.toLowerCase();
  const classes = meaningfulClasses(el, 3).sort().join('.');
  const childShape = Array.from(el.children)
    .slice(0, 6)
    .map((c) => c.tagName.toLowerCase())
    .join(',');
  return `${tag}${classes ? `.${classes}` : ''}[${childShape}]`;
}
